// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`, `hash`, `partial_cmp`, `partial_cmp`, `partial_cmp`


            

            class DecryptResult  {
                final Uint8List plaintext;
final String messageKeysHash;
final List<String>? senderAddresses;

                const DecryptResult({required this.plaintext ,required this.messageKeysHash ,this.senderAddresses ,});

                
                

                
        @override
        int get hashCode => plaintext.hashCode^messageKeysHash.hashCode^senderAddresses.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is DecryptResult &&
                runtimeType == other.runtimeType
                && plaintext == other.plaintext&& messageKeysHash == other.messageKeysHash&& senderAddresses == other.senderAddresses;
        
            }

class EncryptResult  {
                final Uint8List ciphertext;
final String? receiverAddress;
final String messageKeysHash;
final List<String>? senderAddresses;

                const EncryptResult({required this.ciphertext ,this.receiverAddress ,required this.messageKeysHash ,this.senderAddresses ,});

                
                

                
        @override
        int get hashCode => ciphertext.hashCode^receiverAddress.hashCode^messageKeysHash.hashCode^senderAddresses.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is EncryptResult &&
                runtimeType == other.runtimeType
                && ciphertext == other.ciphertext&& receiverAddress == other.receiverAddress&& messageKeysHash == other.messageKeysHash&& senderAddresses == other.senderAddresses;
        
            }

class KeychatIdentityKey  {
                final U8Array33 publicKey;

                const KeychatIdentityKey({required this.publicKey ,});

                
                

                
        @override
        int get hashCode => publicKey.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is KeychatIdentityKey &&
                runtimeType == other.runtimeType
                && publicKey == other.publicKey;
        
            }

class KeychatIdentityKeyPair  {
                final U8Array33 identityKey;
final U8Array32 privateKey;

                const KeychatIdentityKeyPair({required this.identityKey ,required this.privateKey ,});

                
                

                
        @override
        int get hashCode => identityKey.hashCode^privateKey.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is KeychatIdentityKeyPair &&
                runtimeType == other.runtimeType
                && identityKey == other.identityKey&& privateKey == other.privateKey;
        
            }

class KeychatProtocolAddress  {
                final String name;
final int deviceId;

                const KeychatProtocolAddress({required this.name ,required this.deviceId ,});

                
                

                
        @override
        int get hashCode => name.hashCode^deviceId.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is KeychatProtocolAddress &&
                runtimeType == other.runtimeType
                && name == other.name&& deviceId == other.deviceId;
        
            }

class KeychatSignalSession  {
                final String? aliceSenderRatchetKey;
final String address;
final int device;
final String? bobSenderRatchetKey;
final String record;
final String? bobAddress;
final String? aliceAddresses;

                const KeychatSignalSession({this.aliceSenderRatchetKey ,required this.address ,required this.device ,this.bobSenderRatchetKey ,required this.record ,this.bobAddress ,this.aliceAddresses ,});

                
                

                
        @override
        int get hashCode => aliceSenderRatchetKey.hashCode^address.hashCode^device.hashCode^bobSenderRatchetKey.hashCode^record.hashCode^bobAddress.hashCode^aliceAddresses.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is KeychatSignalSession &&
                runtimeType == other.runtimeType
                && aliceSenderRatchetKey == other.aliceSenderRatchetKey&& address == other.address&& device == other.device&& bobSenderRatchetKey == other.bobSenderRatchetKey&& record == other.record&& bobAddress == other.bobAddress&& aliceAddresses == other.aliceAddresses;
        
            }

class KyberPreKeyResult  {
                final int kyberPreKeyId;
final Uint8List kyberPreKeyPublic;
final Uint8List kyberPreKeySignature;
final Uint8List kyberPreKeyRecord;

                const KyberPreKeyResult({required this.kyberPreKeyId ,required this.kyberPreKeyPublic ,required this.kyberPreKeySignature ,required this.kyberPreKeyRecord ,});

                
                

                
        @override
        int get hashCode => kyberPreKeyId.hashCode^kyberPreKeyPublic.hashCode^kyberPreKeySignature.hashCode^kyberPreKeyRecord.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is KyberPreKeyResult &&
                runtimeType == other.runtimeType
                && kyberPreKeyId == other.kyberPreKeyId&& kyberPreKeyPublic == other.kyberPreKeyPublic&& kyberPreKeySignature == other.kyberPreKeySignature&& kyberPreKeyRecord == other.kyberPreKeyRecord;
        
            }

class PreKeyResult  {
                final int preKeyId;
final Uint8List preKeyPublic;
final Uint8List preKeyRecord;

                const PreKeyResult({required this.preKeyId ,required this.preKeyPublic ,required this.preKeyRecord ,});

                
                

                
        @override
        int get hashCode => preKeyId.hashCode^preKeyPublic.hashCode^preKeyRecord.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PreKeyResult &&
                runtimeType == other.runtimeType
                && preKeyId == other.preKeyId&& preKeyPublic == other.preKeyPublic&& preKeyRecord == other.preKeyRecord;
        
            }

class PreKeySignalMessageInfo  {
                final String identityKey;
final int signedPreKeyId;

                const PreKeySignalMessageInfo({required this.identityKey ,required this.signedPreKeyId ,});

                
                

                
        @override
        int get hashCode => identityKey.hashCode^signedPreKeyId.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PreKeySignalMessageInfo &&
                runtimeType == other.runtimeType
                && identityKey == other.identityKey&& signedPreKeyId == other.signedPreKeyId;
        
            }

class SignalKeyPair  {
                final Uint8List privateKey;
final Uint8List publicKey;

                const SignalKeyPair({required this.privateKey ,required this.publicKey ,});

                
                

                
        @override
        int get hashCode => privateKey.hashCode^publicKey.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SignalKeyPair &&
                runtimeType == other.runtimeType
                && privateKey == other.privateKey&& publicKey == other.publicKey;
        
            }

class SignedPreKeyResult  {
                final int signedPreKeyId;
final Uint8List signedPreKeyPublic;
final Uint8List signedPreKeySignature;
final Uint8List signedPreKeyRecord;

                const SignedPreKeyResult({required this.signedPreKeyId ,required this.signedPreKeyPublic ,required this.signedPreKeySignature ,required this.signedPreKeyRecord ,});

                
                

                
        @override
        int get hashCode => signedPreKeyId.hashCode^signedPreKeyPublic.hashCode^signedPreKeySignature.hashCode^signedPreKeyRecord.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SignedPreKeyResult &&
                runtimeType == other.runtimeType
                && signedPreKeyId == other.signedPreKeyId&& signedPreKeyPublic == other.signedPreKeyPublic&& signedPreKeySignature == other.signedPreKeySignature&& signedPreKeyRecord == other.signedPreKeyRecord;
        
            }
            