// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api_signal/types.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `_init_keypair`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RUNTIME_V1`, `STORE_V1`, `SignalStoreV1`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`


            /// init db and KeyChatSignalProtocolStore, this is used for testing
Future<void>  init({required String dbPath , required KeychatIdentityKeyPair keyPair , required int registrationId }) => RustLib.instance.api.crateApiSignalV1Init(dbPath: dbPath, keyPair: keyPair, registrationId: registrationId);

/// init db
Future<void>  initSignalDb({required String dbPath }) => RustLib.instance.api.crateApiSignalV1InitSignalDb(dbPath: dbPath);

/// close db
Future<void>  closeSignalDb() => RustLib.instance.api.crateApiSignalV1CloseSignalDb();

/// init KeyChatSignalProtocolStore
Future<void>  initKeypair({required KeychatIdentityKeyPair keyPair , required int registrationId }) => RustLib.instance.api.crateApiSignalV1InitKeypair(keyPair: keyPair, registrationId: registrationId);

Future<SignedPreKeyResult>  generateSignedPreKeyApi({required KeychatIdentityKeyPair keyPair , required List<int> signalIdentityPrivateKey }) => RustLib.instance.api.crateApiSignalV1GenerateSignedPreKeyApi(keyPair: keyPair, signalIdentityPrivateKey: signalIdentityPrivateKey);

Future<Uint8List>  getSignedPreKeyApi({required KeychatIdentityKeyPair keyPair , required int signedPreKeyId }) => RustLib.instance.api.crateApiSignalV1GetSignedPreKeyApi(keyPair: keyPair, signedPreKeyId: signedPreKeyId);

Future<void>  storeSignedPreKeyApi({required KeychatIdentityKeyPair keyPair , required int signedPreKeyId , required List<int> signedPreKeyRecord }) => RustLib.instance.api.crateApiSignalV1StoreSignedPreKeyApi(keyPair: keyPair, signedPreKeyId: signedPreKeyId, signedPreKeyRecord: signedPreKeyRecord);

Future<PreKeyResult>  generatePrekeyApi({required KeychatIdentityKeyPair keyPair }) => RustLib.instance.api.crateApiSignalV1GeneratePrekeyApi(keyPair: keyPair);

Future<Uint8List>  getPreKeyApi({required KeychatIdentityKeyPair keyPair , required int preKeyId }) => RustLib.instance.api.crateApiSignalV1GetPreKeyApi(keyPair: keyPair, preKeyId: preKeyId);

Future<void>  storePreKeyApi({required KeychatIdentityKeyPair keyPair , required int preKeyId , required List<int> preKeyRecord }) => RustLib.instance.api.crateApiSignalV1StorePreKeyApi(keyPair: keyPair, preKeyId: preKeyId, preKeyRecord: preKeyRecord);

Future<void>  processPreKeyBundleApi({required KeychatIdentityKeyPair keyPair , required KeychatProtocolAddress remoteAddress , required int registrationId , required int deviceId , required KeychatIdentityKey identityKey , required int signedPreKeyId , required List<int> signedPreKeyPublic , required List<int> signedPreKeySignature , required int preKeyId , required List<int> preKeyPublic }) => RustLib.instance.api.crateApiSignalV1ProcessPreKeyBundleApi(keyPair: keyPair, remoteAddress: remoteAddress, registrationId: registrationId, deviceId: deviceId, identityKey: identityKey, signedPreKeyId: signedPreKeyId, signedPreKeyPublic: signedPreKeyPublic, signedPreKeySignature: signedPreKeySignature, preKeyId: preKeyId, preKeyPublic: preKeyPublic);

Future<EncryptResult>  encryptSignal({required KeychatIdentityKeyPair keyPair , required String ptext , required KeychatProtocolAddress remoteAddress , bool? isPrekey }) => RustLib.instance.api.crateApiSignalV1EncryptSignal(keyPair: keyPair, ptext: ptext, remoteAddress: remoteAddress, isPrekey: isPrekey);

Future<PreKeySignalMessageInfo>  parseIdentityFromPrekeySignalMessage({required List<int> ciphertext }) => RustLib.instance.api.crateApiSignalV1ParseIdentityFromPrekeySignalMessage(ciphertext: ciphertext);

Future<bool>  parseIsPrekeySignalMessage({required List<int> ciphertext }) => RustLib.instance.api.crateApiSignalV1ParseIsPrekeySignalMessage(ciphertext: ciphertext);

Future<SignalKeyPair>  generateSignalIds() => RustLib.instance.api.crateApiSignalV1GenerateSignalIds();

Future<DecryptResult>  decryptSignal({required KeychatIdentityKeyPair keyPair , required List<int> ciphertext , required KeychatProtocolAddress remoteAddress , required int roomId , required bool isPrekey }) => RustLib.instance.api.crateApiSignalV1DecryptSignal(keyPair: keyPair, ciphertext: ciphertext, remoteAddress: remoteAddress, roomId: roomId, isPrekey: isPrekey);

Future<KeychatSignalSession?>  sessionContainAliceAddr({required KeychatIdentityKeyPair keyPair , required String address }) => RustLib.instance.api.crateApiSignalV1SessionContainAliceAddr(keyPair: keyPair, address: address);

Future<bool>  updateAliceAddr({required KeychatIdentityKeyPair keyPair , required String address , required String deviceId , required String aliceAddr }) => RustLib.instance.api.crateApiSignalV1UpdateAliceAddr(keyPair: keyPair, address: address, deviceId: deviceId, aliceAddr: aliceAddr);

Future<bool>  containsSession({required KeychatIdentityKeyPair keyPair , required KeychatProtocolAddress address }) => RustLib.instance.api.crateApiSignalV1ContainsSession(keyPair: keyPair, address: address);

Future<bool>  deleteSessionByDeviceId({required KeychatIdentityKeyPair keyPair , required int deviceId }) => RustLib.instance.api.crateApiSignalV1DeleteSessionByDeviceId(keyPair: keyPair, deviceId: deviceId);

Future<bool>  deleteSession({required KeychatIdentityKeyPair keyPair , required KeychatProtocolAddress address }) => RustLib.instance.api.crateApiSignalV1DeleteSession(keyPair: keyPair, address: address);

Future<List<String>>  getAllAliceAddrs({required KeychatIdentityKeyPair keyPair }) => RustLib.instance.api.crateApiSignalV1GetAllAliceAddrs(keyPair: keyPair);

Future<KeychatSignalSession?>  getSession({required KeychatIdentityKeyPair keyPair , required String address , required String deviceId }) => RustLib.instance.api.crateApiSignalV1GetSession(keyPair: keyPair, address: address, deviceId: deviceId);

/// * IdentityStore function
/// 
Future<bool>  deleteIdentity({required KeychatIdentityKeyPair keyPair , required String address }) => RustLib.instance.api.crateApiSignalV1DeleteIdentity(keyPair: keyPair, address: address);

Future<KeychatIdentityKey?>  getIdentity({required KeychatIdentityKeyPair keyPair , required KeychatProtocolAddress address }) => RustLib.instance.api.crateApiSignalV1GetIdentity(keyPair: keyPair, address: address);

            
            