// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api_cashu.dart';
import 'api_cashu/types.dart';
import 'api_cashu_v1.dart';
import 'api_mls.dart';
import 'api_mls/types.dart';
import 'api_nostr.dart';
import 'api_signal.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AmountPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmountPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CurrencyUnitPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnitPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MintUrlPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrlPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MnemonicPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MnemonicInfoPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfoPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MultiMintWalletPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWalletPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WalletPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw);

@protected Amount dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(dynamic raw);

@protected CurrencyUnit dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(dynamic raw);

@protected MintUrl dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(dynamic raw);

@protected MnemonicInfo dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(dynamic raw);

@protected Wallet dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(dynamic raw);

@protected Mnemonic dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(dynamic raw);

@protected MnemonicInfo dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(dynamic raw);

@protected MultiMintWallet dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(dynamic raw);

@protected Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

@protected Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw);

@protected Map<String, List<Uint8List>> dco_decode_Map_String_list_list_prim_u_8_strict_None(dynamic raw);

@protected Map<String, BigInt?> dco_decode_Map_String_opt_box_autoadd_u_64_None(dynamic raw);

@protected Amount dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(dynamic raw);

@protected CurrencyUnit dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(dynamic raw);

@protected MintUrl dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(dynamic raw);

@protected Mnemonic dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(dynamic raw);

@protected MnemonicInfo dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(dynamic raw);

@protected MultiMintWallet dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(dynamic raw);

@protected Wallet dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(dynamic raw);

@protected Set<String> dco_decode_Set_String_None(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected AddMembersResult dco_decode_add_members_result(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected bool dco_decode_box_autoadd_bool(dynamic raw);

@protected KeychatIdentityKey dco_decode_box_autoadd_keychat_identity_key(dynamic raw);

@protected KeychatIdentityKeyPair dco_decode_box_autoadd_keychat_identity_key_pair(dynamic raw);

@protected KeychatProtocolAddress dco_decode_box_autoadd_keychat_protocol_address(dynamic raw);

@protected KeychatSignalSession dco_decode_box_autoadd_keychat_signal_session(dynamic raw);

@protected MintCashuInfo dco_decode_box_autoadd_mint_cashu_info(dynamic raw);

@protected int dco_decode_box_autoadd_u_32(dynamic raw);

@protected BigInt dco_decode_box_autoadd_u_64(dynamic raw);

@protected CashuProofsV1ToV2 dco_decode_cashu_proofs_v_1_to_v_2(dynamic raw);

@protected CashuV1ToV2 dco_decode_cashu_v_1_to_v_2(dynamic raw);

@protected CommitResult dco_decode_commit_result(dynamic raw);

@protected CommitTypeResult dco_decode_commit_type_result(dynamic raw);

@protected ContactCashu dco_decode_contact_cashu(dynamic raw);

@protected DecryptedMessage dco_decode_decrypted_message(dynamic raw);

@protected GroupExtensionResult dco_decode_group_extension_result(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected InvoiceInfo dco_decode_invoice_info(dynamic raw);

@protected InvoiceStatus dco_decode_invoice_status(dynamic raw);

@protected KeyPackageResult dco_decode_key_package_result(dynamic raw);

@protected KeychatIdentityKey dco_decode_keychat_identity_key(dynamic raw);

@protected KeychatIdentityKeyPair dco_decode_keychat_identity_key_pair(dynamic raw);

@protected KeychatProtocolAddress dco_decode_keychat_protocol_address(dynamic raw);

@protected KeychatSignalSession dco_decode_keychat_signal_session(dynamic raw);

@protected List<String> dco_decode_list_String(dynamic raw);

@protected List<ContactCashu> dco_decode_list_contact_cashu(dynamic raw);

@protected List<List<String>> dco_decode_list_list_String(dynamic raw);

@protected List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

@protected List<MintCashu> dco_decode_list_mint_cashu(dynamic raw);

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected List<(MintUrl,Amount)> dco_decode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_mint_url_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_amount(dynamic raw);

@protected List<(String,bool)> dco_decode_list_record_string_bool(dynamic raw);

@protected List<(String,List<Uint8List>)> dco_decode_list_record_string_list_list_prim_u_8_strict(dynamic raw);

@protected List<(String,BigInt?)> dco_decode_list_record_string_opt_box_autoadd_u_64(dynamic raw);

@protected List<(String,String)> dco_decode_list_record_string_string(dynamic raw);

@protected List<Secp256k1Account> dco_decode_list_secp_256_k_1_account(dynamic raw);

@protected List<Transaction> dco_decode_list_transaction(dynamic raw);

@protected MessageInType dco_decode_message_in_type(dynamic raw);

@protected MessageResult dco_decode_message_result(dynamic raw);

@protected MintCashu dco_decode_mint_cashu(dynamic raw);

@protected MintCashuInfo dco_decode_mint_cashu_info(dynamic raw);

@protected NostrEvent dco_decode_nostr_event(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

@protected KeychatIdentityKey? dco_decode_opt_box_autoadd_keychat_identity_key(dynamic raw);

@protected KeychatSignalSession? dco_decode_opt_box_autoadd_keychat_signal_session(dynamic raw);

@protected MintCashuInfo? dco_decode_opt_box_autoadd_mint_cashu_info(dynamic raw);

@protected int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

@protected BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

@protected List<String>? dco_decode_opt_list_String(dynamic raw);

@protected List<List<String>>? dco_decode_opt_list_list_String(dynamic raw);

@protected Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

@protected (MintUrl,Amount) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_mint_url_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_amount(dynamic raw);

@protected (Uint8List,Uint8List) dco_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw);

@protected (Uint8List,String?,String,List<String>?) dco_decode_record_list_prim_u_8_strict_opt_string_string_opt_list_string(dynamic raw);

@protected (Uint8List,String,List<String>?) dco_decode_record_list_prim_u_8_strict_string_opt_list_string(dynamic raw);

@protected (List<String>,Set<String>) dco_decode_record_list_string_set_string_none(dynamic raw);

@protected (List<String>,String,Set<String>) dco_decode_record_list_string_string_set_string_none(dynamic raw);

@protected (String,bool) dco_decode_record_string_bool(dynamic raw);

@protected (String,List<Uint8List>) dco_decode_record_string_list_list_prim_u_8_strict(dynamic raw);

@protected (String,List<String>) dco_decode_record_string_list_string(dynamic raw);

@protected (String,BigInt?) dco_decode_record_string_opt_box_autoadd_u_64(dynamic raw);

@protected (String,String) dco_decode_record_string_string(dynamic raw);

@protected (String,int) dco_decode_record_string_u_32(dynamic raw);

@protected (int,Uint8List,Uint8List) dco_decode_record_u_32_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw);

@protected (int,Uint8List,Uint8List,Uint8List) dco_decode_record_u_32_list_prim_u_8_strict_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw);

@protected (BigInt,BigInt) dco_decode_record_u_64_u_64(dynamic raw);

@protected (BigInt,BigInt,BigInt) dco_decode_record_usize_usize_usize(dynamic raw);

@protected Secp256k1Account dco_decode_secp_256_k_1_account(dynamic raw);

@protected Secp256k1SimpleAccount dco_decode_secp_256_k_1_simple_account(dynamic raw);

@protected SendStampsResult dco_decode_send_stamps_result(dynamic raw);

@protected TokenInfo dco_decode_token_info(dynamic raw);

@protected Transaction dco_decode_transaction(dynamic raw);

@protected TransactionDirection dco_decode_transaction_direction(dynamic raw);

@protected TransactionKind dco_decode_transaction_kind(dynamic raw);

@protected TransactionStatus dco_decode_transaction_status(dynamic raw);

@protected int dco_decode_u_16(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected U8Array32 dco_decode_u_8_array_32(dynamic raw);

@protected U8Array33 dco_decode_u_8_array_33(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected Amount sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(SseDeserializer deserializer);

@protected CurrencyUnit sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(SseDeserializer deserializer);

@protected MintUrl sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(SseDeserializer deserializer);

@protected MnemonicInfo sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(SseDeserializer deserializer);

@protected Wallet sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(SseDeserializer deserializer);

@protected Mnemonic sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(SseDeserializer deserializer);

@protected MnemonicInfo sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(SseDeserializer deserializer);

@protected MultiMintWallet sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(SseDeserializer deserializer);

@protected Map<String, String> sse_decode_Map_String_String_None(SseDeserializer deserializer);

@protected Map<String, bool> sse_decode_Map_String_bool_None(SseDeserializer deserializer);

@protected Map<String, List<Uint8List>> sse_decode_Map_String_list_list_prim_u_8_strict_None(SseDeserializer deserializer);

@protected Map<String, BigInt?> sse_decode_Map_String_opt_box_autoadd_u_64_None(SseDeserializer deserializer);

@protected Amount sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(SseDeserializer deserializer);

@protected CurrencyUnit sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(SseDeserializer deserializer);

@protected MintUrl sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(SseDeserializer deserializer);

@protected Mnemonic sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(SseDeserializer deserializer);

@protected MnemonicInfo sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(SseDeserializer deserializer);

@protected MultiMintWallet sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(SseDeserializer deserializer);

@protected Wallet sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(SseDeserializer deserializer);

@protected Set<String> sse_decode_Set_String_None(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected AddMembersResult sse_decode_add_members_result(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

@protected KeychatIdentityKey sse_decode_box_autoadd_keychat_identity_key(SseDeserializer deserializer);

@protected KeychatIdentityKeyPair sse_decode_box_autoadd_keychat_identity_key_pair(SseDeserializer deserializer);

@protected KeychatProtocolAddress sse_decode_box_autoadd_keychat_protocol_address(SseDeserializer deserializer);

@protected KeychatSignalSession sse_decode_box_autoadd_keychat_signal_session(SseDeserializer deserializer);

@protected MintCashuInfo sse_decode_box_autoadd_mint_cashu_info(SseDeserializer deserializer);

@protected int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

@protected CashuProofsV1ToV2 sse_decode_cashu_proofs_v_1_to_v_2(SseDeserializer deserializer);

@protected CashuV1ToV2 sse_decode_cashu_v_1_to_v_2(SseDeserializer deserializer);

@protected CommitResult sse_decode_commit_result(SseDeserializer deserializer);

@protected CommitTypeResult sse_decode_commit_type_result(SseDeserializer deserializer);

@protected ContactCashu sse_decode_contact_cashu(SseDeserializer deserializer);

@protected DecryptedMessage sse_decode_decrypted_message(SseDeserializer deserializer);

@protected GroupExtensionResult sse_decode_group_extension_result(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected InvoiceInfo sse_decode_invoice_info(SseDeserializer deserializer);

@protected InvoiceStatus sse_decode_invoice_status(SseDeserializer deserializer);

@protected KeyPackageResult sse_decode_key_package_result(SseDeserializer deserializer);

@protected KeychatIdentityKey sse_decode_keychat_identity_key(SseDeserializer deserializer);

@protected KeychatIdentityKeyPair sse_decode_keychat_identity_key_pair(SseDeserializer deserializer);

@protected KeychatProtocolAddress sse_decode_keychat_protocol_address(SseDeserializer deserializer);

@protected KeychatSignalSession sse_decode_keychat_signal_session(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected List<ContactCashu> sse_decode_list_contact_cashu(SseDeserializer deserializer);

@protected List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

@protected List<Uint8List> sse_decode_list_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<MintCashu> sse_decode_list_mint_cashu(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<(MintUrl,Amount)> sse_decode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_mint_url_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_amount(SseDeserializer deserializer);

@protected List<(String,bool)> sse_decode_list_record_string_bool(SseDeserializer deserializer);

@protected List<(String,List<Uint8List>)> sse_decode_list_record_string_list_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<(String,BigInt?)> sse_decode_list_record_string_opt_box_autoadd_u_64(SseDeserializer deserializer);

@protected List<(String,String)> sse_decode_list_record_string_string(SseDeserializer deserializer);

@protected List<Secp256k1Account> sse_decode_list_secp_256_k_1_account(SseDeserializer deserializer);

@protected List<Transaction> sse_decode_list_transaction(SseDeserializer deserializer);

@protected MessageInType sse_decode_message_in_type(SseDeserializer deserializer);

@protected MessageResult sse_decode_message_result(SseDeserializer deserializer);

@protected MintCashu sse_decode_mint_cashu(SseDeserializer deserializer);

@protected MintCashuInfo sse_decode_mint_cashu_info(SseDeserializer deserializer);

@protected NostrEvent sse_decode_nostr_event(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

@protected KeychatIdentityKey? sse_decode_opt_box_autoadd_keychat_identity_key(SseDeserializer deserializer);

@protected KeychatSignalSession? sse_decode_opt_box_autoadd_keychat_signal_session(SseDeserializer deserializer);

@protected MintCashuInfo? sse_decode_opt_box_autoadd_mint_cashu_info(SseDeserializer deserializer);

@protected int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

@protected BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

@protected List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

@protected List<List<String>>? sse_decode_opt_list_list_String(SseDeserializer deserializer);

@protected Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

@protected (MintUrl,Amount) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_mint_url_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_amount(SseDeserializer deserializer);

@protected (Uint8List,Uint8List) sse_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(SseDeserializer deserializer);

@protected (Uint8List,String?,String,List<String>?) sse_decode_record_list_prim_u_8_strict_opt_string_string_opt_list_string(SseDeserializer deserializer);

@protected (Uint8List,String,List<String>?) sse_decode_record_list_prim_u_8_strict_string_opt_list_string(SseDeserializer deserializer);

@protected (List<String>,Set<String>) sse_decode_record_list_string_set_string_none(SseDeserializer deserializer);

@protected (List<String>,String,Set<String>) sse_decode_record_list_string_string_set_string_none(SseDeserializer deserializer);

@protected (String,bool) sse_decode_record_string_bool(SseDeserializer deserializer);

@protected (String,List<Uint8List>) sse_decode_record_string_list_list_prim_u_8_strict(SseDeserializer deserializer);

@protected (String,List<String>) sse_decode_record_string_list_string(SseDeserializer deserializer);

@protected (String,BigInt?) sse_decode_record_string_opt_box_autoadd_u_64(SseDeserializer deserializer);

@protected (String,String) sse_decode_record_string_string(SseDeserializer deserializer);

@protected (String,int) sse_decode_record_string_u_32(SseDeserializer deserializer);

@protected (int,Uint8List,Uint8List) sse_decode_record_u_32_list_prim_u_8_strict_list_prim_u_8_strict(SseDeserializer deserializer);

@protected (int,Uint8List,Uint8List,Uint8List) sse_decode_record_u_32_list_prim_u_8_strict_list_prim_u_8_strict_list_prim_u_8_strict(SseDeserializer deserializer);

@protected (BigInt,BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer);

@protected (BigInt,BigInt,BigInt) sse_decode_record_usize_usize_usize(SseDeserializer deserializer);

@protected Secp256k1Account sse_decode_secp_256_k_1_account(SseDeserializer deserializer);

@protected Secp256k1SimpleAccount sse_decode_secp_256_k_1_simple_account(SseDeserializer deserializer);

@protected SendStampsResult sse_decode_send_stamps_result(SseDeserializer deserializer);

@protected TokenInfo sse_decode_token_info(SseDeserializer deserializer);

@protected Transaction sse_decode_transaction(SseDeserializer deserializer);

@protected TransactionDirection sse_decode_transaction_direction(SseDeserializer deserializer);

@protected TransactionKind sse_decode_transaction_kind(SseDeserializer deserializer);

@protected TransactionStatus sse_decode_transaction_status(SseDeserializer deserializer);

@protected int sse_decode_u_16(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer);

@protected U8Array33 sse_decode_u_8_array_33(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(Amount self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(CurrencyUnit self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(MintUrl self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(MnemonicInfo self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(Wallet self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(Mnemonic self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(MnemonicInfo self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(MultiMintWallet self, SseSerializer serializer);

@protected void sse_encode_Map_String_String_None(Map<String, String> self, SseSerializer serializer);

@protected void sse_encode_Map_String_bool_None(Map<String, bool> self, SseSerializer serializer);

@protected void sse_encode_Map_String_list_list_prim_u_8_strict_None(Map<String, List<Uint8List>> self, SseSerializer serializer);

@protected void sse_encode_Map_String_opt_box_autoadd_u_64_None(Map<String, BigInt?> self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(Amount self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(CurrencyUnit self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(MintUrl self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(Mnemonic self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(MnemonicInfo self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(MultiMintWallet self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(Wallet self, SseSerializer serializer);

@protected void sse_encode_Set_String_None(Set<String> self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_add_members_result(AddMembersResult self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_keychat_identity_key(KeychatIdentityKey self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_keychat_identity_key_pair(KeychatIdentityKeyPair self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_keychat_protocol_address(KeychatProtocolAddress self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_keychat_signal_session(KeychatSignalSession self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_mint_cashu_info(MintCashuInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_cashu_proofs_v_1_to_v_2(CashuProofsV1ToV2 self, SseSerializer serializer);

@protected void sse_encode_cashu_v_1_to_v_2(CashuV1ToV2 self, SseSerializer serializer);

@protected void sse_encode_commit_result(CommitResult self, SseSerializer serializer);

@protected void sse_encode_commit_type_result(CommitTypeResult self, SseSerializer serializer);

@protected void sse_encode_contact_cashu(ContactCashu self, SseSerializer serializer);

@protected void sse_encode_decrypted_message(DecryptedMessage self, SseSerializer serializer);

@protected void sse_encode_group_extension_result(GroupExtensionResult self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_invoice_info(InvoiceInfo self, SseSerializer serializer);

@protected void sse_encode_invoice_status(InvoiceStatus self, SseSerializer serializer);

@protected void sse_encode_key_package_result(KeyPackageResult self, SseSerializer serializer);

@protected void sse_encode_keychat_identity_key(KeychatIdentityKey self, SseSerializer serializer);

@protected void sse_encode_keychat_identity_key_pair(KeychatIdentityKeyPair self, SseSerializer serializer);

@protected void sse_encode_keychat_protocol_address(KeychatProtocolAddress self, SseSerializer serializer);

@protected void sse_encode_keychat_signal_session(KeychatSignalSession self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_contact_cashu(List<ContactCashu> self, SseSerializer serializer);

@protected void sse_encode_list_list_String(List<List<String>> self, SseSerializer serializer);

@protected void sse_encode_list_list_prim_u_8_strict(List<Uint8List> self, SseSerializer serializer);

@protected void sse_encode_list_mint_cashu(List<MintCashu> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_mint_url_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_amount(List<(MintUrl,Amount)> self, SseSerializer serializer);

@protected void sse_encode_list_record_string_bool(List<(String,bool)> self, SseSerializer serializer);

@protected void sse_encode_list_record_string_list_list_prim_u_8_strict(List<(String,List<Uint8List>)> self, SseSerializer serializer);

@protected void sse_encode_list_record_string_opt_box_autoadd_u_64(List<(String,BigInt?)> self, SseSerializer serializer);

@protected void sse_encode_list_record_string_string(List<(String,String)> self, SseSerializer serializer);

@protected void sse_encode_list_secp_256_k_1_account(List<Secp256k1Account> self, SseSerializer serializer);

@protected void sse_encode_list_transaction(List<Transaction> self, SseSerializer serializer);

@protected void sse_encode_message_in_type(MessageInType self, SseSerializer serializer);

@protected void sse_encode_message_result(MessageResult self, SseSerializer serializer);

@protected void sse_encode_mint_cashu(MintCashu self, SseSerializer serializer);

@protected void sse_encode_mint_cashu_info(MintCashuInfo self, SseSerializer serializer);

@protected void sse_encode_nostr_event(NostrEvent self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_keychat_identity_key(KeychatIdentityKey? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_keychat_signal_session(KeychatSignalSession? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_mint_cashu_info(MintCashuInfo? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

@protected void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

@protected void sse_encode_opt_list_list_String(List<List<String>>? self, SseSerializer serializer);

@protected void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer);

@protected void sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_mint_url_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_amount((MintUrl,Amount) self, SseSerializer serializer);

@protected void sse_encode_record_list_prim_u_8_strict_list_prim_u_8_strict((Uint8List,Uint8List) self, SseSerializer serializer);

@protected void sse_encode_record_list_prim_u_8_strict_opt_string_string_opt_list_string((Uint8List,String?,String,List<String>?) self, SseSerializer serializer);

@protected void sse_encode_record_list_prim_u_8_strict_string_opt_list_string((Uint8List,String,List<String>?) self, SseSerializer serializer);

@protected void sse_encode_record_list_string_set_string_none((List<String>,Set<String>) self, SseSerializer serializer);

@protected void sse_encode_record_list_string_string_set_string_none((List<String>,String,Set<String>) self, SseSerializer serializer);

@protected void sse_encode_record_string_bool((String,bool) self, SseSerializer serializer);

@protected void sse_encode_record_string_list_list_prim_u_8_strict((String,List<Uint8List>) self, SseSerializer serializer);

@protected void sse_encode_record_string_list_string((String,List<String>) self, SseSerializer serializer);

@protected void sse_encode_record_string_opt_box_autoadd_u_64((String,BigInt?) self, SseSerializer serializer);

@protected void sse_encode_record_string_string((String,String) self, SseSerializer serializer);

@protected void sse_encode_record_string_u_32((String,int) self, SseSerializer serializer);

@protected void sse_encode_record_u_32_list_prim_u_8_strict_list_prim_u_8_strict((int,Uint8List,Uint8List) self, SseSerializer serializer);

@protected void sse_encode_record_u_32_list_prim_u_8_strict_list_prim_u_8_strict_list_prim_u_8_strict((int,Uint8List,Uint8List,Uint8List) self, SseSerializer serializer);

@protected void sse_encode_record_u_64_u_64((BigInt,BigInt) self, SseSerializer serializer);

@protected void sse_encode_record_usize_usize_usize((BigInt,BigInt,BigInt) self, SseSerializer serializer);

@protected void sse_encode_secp_256_k_1_account(Secp256k1Account self, SseSerializer serializer);

@protected void sse_encode_secp_256_k_1_simple_account(Secp256k1SimpleAccount self, SseSerializer serializer);

@protected void sse_encode_send_stamps_result(SendStampsResult self, SseSerializer serializer);

@protected void sse_encode_token_info(TokenInfo self, SseSerializer serializer);

@protected void sse_encode_transaction(Transaction self, SseSerializer serializer);

@protected void sse_encode_transaction_direction(TransactionDirection self, SseSerializer serializer);

@protected void sse_encode_transaction_kind(TransactionKind self, SseSerializer serializer);

@protected void sse_encode_transaction_status(TransactionStatus self, SseSerializer serializer);

@protected void sse_encode_u_16(int self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer);

@protected void sse_encode_u_8_array_33(U8Array33 self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);
                }
                


// Section: wire_class


        class RustLibWire implements BaseWire {

            factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
              RustLibWire(lib.ffiDynamicLibrary);
        
            /// Holds the symbol lookup function.
            final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                _lookup;
  
            /// The symbols are looked up in [dynamicLibrary].
            RustLibWire(ffi.DynamicLibrary dynamicLibrary)
                : _lookup = dynamicLibrary.lookup;

            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmountPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmountPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmountPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmount = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAmountPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnitPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnitPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnitPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnit = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCurrencyUnitPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrlPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrlPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrlPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrl = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintUrlPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonic = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfoPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfoPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfoPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfo = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMnemonicInfoPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWalletPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWalletPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWalletPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWallet = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMultiMintWalletPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_keychat_rust_ffi_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
        }
        