// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api_cashu/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            

            class Amount  {
                final BigInt field0;

                const Amount({required this.field0 ,});

                
                

                
        @override
        int get hashCode => field0.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is Amount &&
                runtimeType == other.runtimeType
                && field0 == other.field0;
        
            }

enum CurrencyUnit {
                    /// Sat
sat,
/// Msat
msat,
/// Usd
usd,
/// Euro
eur,
/// Auth
auth,
                    ;
                    
                }

class MintUrl  {
                final String field0;

                const MintUrl({required this.field0 ,});

                
                

                
        @override
        int get hashCode => field0.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is MintUrl &&
                runtimeType == other.runtimeType
                && field0 == other.field0;
        
            }

class PublicKey  {
                final Uint8List bytes;

                const PublicKey({required this.bytes ,});

                
                

                
        @override
        int get hashCode => bytes.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is PublicKey &&
                runtimeType == other.runtimeType
                && bytes == other.bytes;
        
            }

class Transaction  {
                final MintUrl mintUrl;
final TransactionDirection direction;
final TransactionKind kind;
final Amount amount;
final Amount fee;
final CurrencyUnit unit;
final List<PublicKey> ys;
final BigInt timestamp;
final String? memo;
final Map<String, String> metadata;

                const Transaction({required this.mintUrl ,required this.direction ,required this.kind ,required this.amount ,required this.fee ,required this.unit ,required this.ys ,required this.timestamp ,this.memo ,required this.metadata ,});

                
                

                
        @override
        int get hashCode => mintUrl.hashCode^direction.hashCode^kind.hashCode^amount.hashCode^fee.hashCode^unit.hashCode^ys.hashCode^timestamp.hashCode^memo.hashCode^metadata.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is Transaction &&
                runtimeType == other.runtimeType
                && mintUrl == other.mintUrl&& direction == other.direction&& kind == other.kind&& amount == other.amount&& fee == other.fee&& unit == other.unit&& ys == other.ys&& timestamp == other.timestamp&& memo == other.memo&& metadata == other.metadata;
        
            }
            