// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AddMembersResult {
  final String queuedMsg;
  final Uint8List welcome;

  const AddMembersResult({
    required this.queuedMsg,
    required this.welcome,
  });

  @override
  int get hashCode => queuedMsg.hashCode ^ welcome.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddMembersResult &&
          runtimeType == other.runtimeType &&
          queuedMsg == other.queuedMsg &&
          welcome == other.welcome;
}

class CommitResult {
  final String sender;
  final CommitTypeResult commitType;
  final List<String>? operatedMembers;

  const CommitResult({
    required this.sender,
    required this.commitType,
    this.operatedMembers,
  });

  @override
  int get hashCode => sender.hashCode ^ commitType.hashCode ^ operatedMembers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommitResult &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          commitType == other.commitType &&
          operatedMembers == other.operatedMembers;
}

enum CommitTypeResult {
  add,
  update,
  remove,
  groupContextExtensions,
  ;
}

class DecryptedMessage {
  final String decryptMsg;
  final String sender;
  final Uint8List? ratchetKey;

  const DecryptedMessage({
    required this.decryptMsg,
    required this.sender,
    this.ratchetKey,
  });

  @override
  int get hashCode => decryptMsg.hashCode ^ sender.hashCode ^ ratchetKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecryptedMessage &&
          runtimeType == other.runtimeType &&
          decryptMsg == other.decryptMsg &&
          sender == other.sender &&
          ratchetKey == other.ratchetKey;
}

class GroupExtensionResult {
  final Uint8List name;
  final Uint8List description;
  final List<Uint8List> adminPubkeys;
  final List<Uint8List> relays;
  final Uint8List status;

  const GroupExtensionResult({
    required this.name,
    required this.description,
    required this.adminPubkeys,
    required this.relays,
    required this.status,
  });

  @override
  int get hashCode => name.hashCode ^ description.hashCode ^ adminPubkeys.hashCode ^ relays.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupExtensionResult &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          adminPubkeys == other.adminPubkeys &&
          relays == other.relays &&
          status == other.status;
}

enum MessageInType {
  application,
  proposal,
  commit,
  welcome,
  groupInfo,
  keyPackage,
  publicMessage,
  custom,
  ;
}

class MessageResult {
  final String encryptMsg;
  final Uint8List? ratchetKey;

  const MessageResult({
    required this.encryptMsg,
    this.ratchetKey,
  });

  @override
  int get hashCode => encryptMsg.hashCode ^ ratchetKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageResult &&
          runtimeType == other.runtimeType &&
          encryptMsg == other.encryptMsg &&
          ratchetKey == other.ratchetKey;
}
