// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api_mls.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_members`, `adder_self_commit`, `admin_commit_leave`, `create_key_package`, `create_mls_group`, `decrypt_msg`, `get_export_secret`, `get_group_config`, `get_lead_node_index`, `get_tree_hash`, `join_mls_group`, `load`, `new`, `normal_member_commit_leave`, `others_commit_normal`, `others_commit_remove_member`, `others_proposal_leave`, `remove_members`, `save`, `self_leave`, `self_update`, `send_msg`, `update`
// These types are ignored because they are not used by any `pub` functions: `Group`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<User>>
abstract class User implements RustOpaqueInterface {
  MlsLitePool get pool;

  OpenMlsRustPersistentCrypto get provider;

  set pool(MlsLitePool pool);

  set provider(OpenMlsRustPersistentCrypto provider);
}
